//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Money.Unifi.pain_001_003_03 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03", IsNullable=false)]
    public partial class Document {
        
        private CustomerCreditTransferInitiationV03 cstmrCdtTrfInitnField;
        
        /// <remarks/>
        public CustomerCreditTransferInitiationV03 CstmrCdtTrfInitn {
            get {
                return this.cstmrCdtTrfInitnField;
            }
            set {
                this.cstmrCdtTrfInitnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class CustomerCreditTransferInitiationV03 {
        
        private GroupHeaderSCT grpHdrField;
        
        private PaymentInstructionInformationSCT[] pmtInfField;
        
        /// <remarks/>
        public GroupHeaderSCT GrpHdr {
            get {
                return this.grpHdrField;
            }
            set {
                this.grpHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PmtInf")]
        public PaymentInstructionInformationSCT[] PmtInf {
            get {
                return this.pmtInfField;
            }
            set {
                this.pmtInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class GroupHeaderSCT {
        
        private string msgIdField;
        
        private System.DateTime creDtTmField;
        
        private string nbOfTxsField;
        
        private decimal ctrlSumField;
        
        private bool ctrlSumFieldSpecified;
        
        private PartyIdentificationSEPA1 initgPtyField;
        
        /// <remarks/>
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDtTm {
            get {
                return this.creDtTmField;
            }
            set {
                this.creDtTmField = value;
            }
        }
        
        /// <remarks/>
        public string NbOfTxs {
            get {
                return this.nbOfTxsField;
            }
            set {
                this.nbOfTxsField = value;
            }
        }
        
        /// <remarks/>
        public decimal CtrlSum {
            get {
                return this.ctrlSumField;
            }
            set {
                this.ctrlSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CtrlSumSpecified {
            get {
                return this.ctrlSumFieldSpecified;
            }
            set {
                this.ctrlSumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationSEPA1 InitgPty {
            get {
                return this.initgPtyField;
            }
            set {
                this.initgPtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class PartyIdentificationSEPA1 {
        
        private string nmField;
        
        private PartySEPAChoice idField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PartySEPAChoice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class PartySEPAChoice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgId", typeof(OrganisationIdentificationSEPAChoice))]
        [System.Xml.Serialization.XmlElementAttribute("PrvtId", typeof(PersonIdentificationSEPA1Choice))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class OrganisationIdentificationSEPAChoice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BICOrBEI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericOrganisationIdentification1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class GenericOrganisationIdentification1 {
        
        private string idField;
        
        private OrganisationIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public OrganisationIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class OrganisationIdentificationSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class CreditorReferenceTypeCodeSEPA {
        
        private DocumentType3CodeSEPA cdField;
        
        /// <remarks/>
        public DocumentType3CodeSEPA Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public enum DocumentType3CodeSEPA {
        
        /// <remarks/>
        SCOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class CreditorReferenceTypeSEPA {
        
        private CreditorReferenceTypeCodeSEPA cdOrPrtryField;
        
        private string issrField;
        
        /// <remarks/>
        public CreditorReferenceTypeCodeSEPA CdOrPrtry {
            get {
                return this.cdOrPrtryField;
            }
            set {
                this.cdOrPrtryField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class CreditorReferenceInformationSEPA1 {
        
        private CreditorReferenceTypeSEPA tpField;
        
        private string refField;
        
        /// <remarks/>
        public CreditorReferenceTypeSEPA Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class StructuredRemittanceInformationSEPA1 {
        
        private CreditorReferenceInformationSEPA1 cdtrRefInfField;
        
        /// <remarks/>
        public CreditorReferenceInformationSEPA1 CdtrRefInf {
            get {
                return this.cdtrRefInfField;
            }
            set {
                this.cdtrRefInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class RemittanceInformationSEPA1Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Strd", typeof(StructuredRemittanceInformationSEPA1))]
        [System.Xml.Serialization.XmlElementAttribute("Ustrd", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class PurposeSEPA {
        
        private string cdField;
        
        /// <remarks/>
        public string Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class CashAccountSEPA2 {
        
        private AccountIdentificationSEPA idField;
        
        /// <remarks/>
        public AccountIdentificationSEPA Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class AccountIdentificationSEPA {
        
        private string iBANField;
        
        /// <remarks/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class FinancialInstitutionIdentificationSEPA1 {
        
        private string bICField;
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class BranchAndFinancialInstitutionIdentificationSEPA1 {
        
        private FinancialInstitutionIdentificationSEPA1 finInstnIdField;
        
        /// <remarks/>
        public FinancialInstitutionIdentificationSEPA1 FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class ActiveOrHistoricCurrencyAndAmountSEPA {
        
        private ActiveOrHistoricCurrencyCodeEUR ccyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ActiveOrHistoricCurrencyCodeEUR Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public enum ActiveOrHistoricCurrencyCodeEUR {
        
        /// <remarks/>
        EUR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class AmountTypeSEPA {
        
        private ActiveOrHistoricCurrencyAndAmountSEPA instdAmtField;
        
        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmountSEPA InstdAmt {
            get {
                return this.instdAmtField;
            }
            set {
                this.instdAmtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class PaymentTypeInformationSCT2 {
        
        private ServiceLevelSEPA svcLvlField;
        
        private CategoryPurposeSEPA ctgyPurpField;
        
        /// <remarks/>
        public ServiceLevelSEPA SvcLvl {
            get {
                return this.svcLvlField;
            }
            set {
                this.svcLvlField = value;
            }
        }
        
        /// <remarks/>
        public CategoryPurposeSEPA CtgyPurp {
            get {
                return this.ctgyPurpField;
            }
            set {
                this.ctgyPurpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class ServiceLevelSEPA {
        
        private string cdField;
        
        /// <remarks/>
        public string Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class CategoryPurposeSEPA {
        
        private string cdField;
        
        /// <remarks/>
        public string Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class PaymentIdentificationSEPA {
        
        private string instrIdField;
        
        private string endToEndIdField;
        
        /// <remarks/>
        public string InstrId {
            get {
                return this.instrIdField;
            }
            set {
                this.instrIdField = value;
            }
        }
        
        /// <remarks/>
        public string EndToEndId {
            get {
                return this.endToEndIdField;
            }
            set {
                this.endToEndIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class CreditTransferTransactionInformationSCT {
        
        private PaymentIdentificationSEPA pmtIdField;
        
        private PaymentTypeInformationSCT2 pmtTpInfField;
        
        private AmountTypeSEPA amtField;
        
        private ChargeBearerTypeSEPACode chrgBrField;
        
        private bool chrgBrFieldSpecified;
        
        private PartyIdentificationSEPA1 ultmtDbtrField;
        
        private BranchAndFinancialInstitutionIdentificationSEPA1 cdtrAgtField;
        
        private PartyIdentificationSEPA2 cdtrField;
        
        private CashAccountSEPA2 cdtrAcctField;
        
        private PartyIdentificationSEPA1 ultmtCdtrField;
        
        private PurposeSEPA purpField;
        
        private RemittanceInformationSEPA1Choice rmtInfField;
        
        /// <remarks/>
        public PaymentIdentificationSEPA PmtId {
            get {
                return this.pmtIdField;
            }
            set {
                this.pmtIdField = value;
            }
        }
        
        /// <remarks/>
        public PaymentTypeInformationSCT2 PmtTpInf {
            get {
                return this.pmtTpInfField;
            }
            set {
                this.pmtTpInfField = value;
            }
        }
        
        /// <remarks/>
        public AmountTypeSEPA Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }
        
        /// <remarks/>
        public ChargeBearerTypeSEPACode ChrgBr {
            get {
                return this.chrgBrField;
            }
            set {
                this.chrgBrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChrgBrSpecified {
            get {
                return this.chrgBrFieldSpecified;
            }
            set {
                this.chrgBrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationSEPA1 UltmtDbtr {
            get {
                return this.ultmtDbtrField;
            }
            set {
                this.ultmtDbtrField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentificationSEPA1 CdtrAgt {
            get {
                return this.cdtrAgtField;
            }
            set {
                this.cdtrAgtField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationSEPA2 Cdtr {
            get {
                return this.cdtrField;
            }
            set {
                this.cdtrField = value;
            }
        }
        
        /// <remarks/>
        public CashAccountSEPA2 CdtrAcct {
            get {
                return this.cdtrAcctField;
            }
            set {
                this.cdtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationSEPA1 UltmtCdtr {
            get {
                return this.ultmtCdtrField;
            }
            set {
                this.ultmtCdtrField = value;
            }
        }
        
        /// <remarks/>
        public PurposeSEPA Purp {
            get {
                return this.purpField;
            }
            set {
                this.purpField = value;
            }
        }
        
        /// <remarks/>
        public RemittanceInformationSEPA1Choice RmtInf {
            get {
                return this.rmtInfField;
            }
            set {
                this.rmtInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public enum ChargeBearerTypeSEPACode {
        
        /// <remarks/>
        SLEV,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class PartyIdentificationSEPA2 {
        
        private string nmField;
        
        private PostalAddressSEPA pstlAdrField;
        
        private PartySEPAChoice idField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddressSEPA PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public PartySEPAChoice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class PostalAddressSEPA {
        
        private string ctryField;
        
        private string[] adrLineField;
        
        /// <remarks/>
        public string Ctry {
            get {
                return this.ctryField;
            }
            set {
                this.ctryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
        public string[] AdrLine {
            get {
                return this.adrLineField;
            }
            set {
                this.adrLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class OthrIdentification {
        
        private OthrIdentificationCode idField;
        
        /// <remarks/>
        public OthrIdentificationCode Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public enum OthrIdentificationCode {
        
        /// <remarks/>
        NOTPROVIDED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class FinancialInstitutionIdentificationSEPA3 {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(OthrIdentification))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class BranchAndFinancialInstitutionIdentificationSEPA3 {
        
        private FinancialInstitutionIdentificationSEPA3 finInstnIdField;
        
        /// <remarks/>
        public FinancialInstitutionIdentificationSEPA3 FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class CashAccountSEPA1 {
        
        private AccountIdentificationSEPA idField;
        
        private string ccyField;
        
        /// <remarks/>
        public AccountIdentificationSEPA Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class PaymentTypeInformationSCT1 {
        
        private Priority2Code instrPrtyField;
        
        private bool instrPrtyFieldSpecified;
        
        private ServiceLevelSEPA svcLvlField;
        
        private CategoryPurposeSEPA ctgyPurpField;
        
        /// <remarks/>
        public Priority2Code InstrPrty {
            get {
                return this.instrPrtyField;
            }
            set {
                this.instrPrtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstrPrtySpecified {
            get {
                return this.instrPrtyFieldSpecified;
            }
            set {
                this.instrPrtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ServiceLevelSEPA SvcLvl {
            get {
                return this.svcLvlField;
            }
            set {
                this.svcLvlField = value;
            }
        }
        
        /// <remarks/>
        public CategoryPurposeSEPA CtgyPurp {
            get {
                return this.ctgyPurpField;
            }
            set {
                this.ctgyPurpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public enum Priority2Code {
        
        /// <remarks/>
        HIGH,
        
        /// <remarks/>
        NORM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class PaymentInstructionInformationSCT {
        
        private string pmtInfIdField;
        
        private PaymentMethodSCTCode pmtMtdField;
        
        private bool btchBookgField;
        
        private bool btchBookgFieldSpecified;
        
        private string nbOfTxsField;
        
        private decimal ctrlSumField;
        
        private bool ctrlSumFieldSpecified;
        
        private PaymentTypeInformationSCT1 pmtTpInfField;
        
        private System.DateTime reqdExctnDtField;
        
        private PartyIdentificationSEPA2 dbtrField;
        
        private CashAccountSEPA1 dbtrAcctField;
        
        private BranchAndFinancialInstitutionIdentificationSEPA3 dbtrAgtField;
        
        private PartyIdentificationSEPA1 ultmtDbtrField;
        
        private ChargeBearerTypeSEPACode chrgBrField;
        
        private bool chrgBrFieldSpecified;
        
        private CreditTransferTransactionInformationSCT[] cdtTrfTxInfField;
        
        /// <remarks/>
        public string PmtInfId {
            get {
                return this.pmtInfIdField;
            }
            set {
                this.pmtInfIdField = value;
            }
        }
        
        /// <remarks/>
        public PaymentMethodSCTCode PmtMtd {
            get {
                return this.pmtMtdField;
            }
            set {
                this.pmtMtdField = value;
            }
        }
        
        /// <remarks/>
        public bool BtchBookg {
            get {
                return this.btchBookgField;
            }
            set {
                this.btchBookgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BtchBookgSpecified {
            get {
                return this.btchBookgFieldSpecified;
            }
            set {
                this.btchBookgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NbOfTxs {
            get {
                return this.nbOfTxsField;
            }
            set {
                this.nbOfTxsField = value;
            }
        }
        
        /// <remarks/>
        public decimal CtrlSum {
            get {
                return this.ctrlSumField;
            }
            set {
                this.ctrlSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CtrlSumSpecified {
            get {
                return this.ctrlSumFieldSpecified;
            }
            set {
                this.ctrlSumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public PaymentTypeInformationSCT1 PmtTpInf {
            get {
                return this.pmtTpInfField;
            }
            set {
                this.pmtTpInfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ReqdExctnDt {
            get {
                return this.reqdExctnDtField;
            }
            set {
                this.reqdExctnDtField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationSEPA2 Dbtr {
            get {
                return this.dbtrField;
            }
            set {
                this.dbtrField = value;
            }
        }
        
        /// <remarks/>
        public CashAccountSEPA1 DbtrAcct {
            get {
                return this.dbtrAcctField;
            }
            set {
                this.dbtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentificationSEPA3 DbtrAgt {
            get {
                return this.dbtrAgtField;
            }
            set {
                this.dbtrAgtField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationSEPA1 UltmtDbtr {
            get {
                return this.ultmtDbtrField;
            }
            set {
                this.ultmtDbtrField = value;
            }
        }
        
        /// <remarks/>
        public ChargeBearerTypeSEPACode ChrgBr {
            get {
                return this.chrgBrField;
            }
            set {
                this.chrgBrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChrgBrSpecified {
            get {
                return this.chrgBrFieldSpecified;
            }
            set {
                this.chrgBrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CdtTrfTxInf")]
        public CreditTransferTransactionInformationSCT[] CdtTrfTxInf {
            get {
                return this.cdtTrfTxInfField;
            }
            set {
                this.cdtTrfTxInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public enum PaymentMethodSCTCode {
        
        /// <remarks/>
        TRF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class PersonIdentificationSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class GenericPersonIdentification1 {
        
        private string idField;
        
        private PersonIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public PersonIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class DateAndPlaceOfBirth {
        
        private System.DateTime birthDtField;
        
        private string prvcOfBirthField;
        
        private string cityOfBirthField;
        
        private string ctryOfBirthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BirthDt {
            get {
                return this.birthDtField;
            }
            set {
                this.birthDtField = value;
            }
        }
        
        /// <remarks/>
        public string PrvcOfBirth {
            get {
                return this.prvcOfBirthField;
            }
            set {
                this.prvcOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CityOfBirth {
            get {
                return this.cityOfBirthField;
            }
            set {
                this.cityOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfBirth {
            get {
                return this.ctryOfBirthField;
            }
            set {
                this.ctryOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.003.03")]
    public partial class PersonIdentificationSEPA1Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DtAndPlcOfBirth", typeof(DateAndPlaceOfBirth))]
        [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericPersonIdentification1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
}
