//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Money.Unifi.pain_002_003_03 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03", IsNullable=false)]
    public partial class Document {
        
        private CustomerPaymentStatusReportV03 cstmrPmtStsRptField;
        
        /// <remarks/>
        public CustomerPaymentStatusReportV03 CstmrPmtStsRpt {
            get {
                return this.cstmrPmtStsRptField;
            }
            set {
                this.cstmrPmtStsRptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class CustomerPaymentStatusReportV03 {
        
        private GroupHeaderSEPA grpHdrField;
        
        private OriginalGroupInformationSEPA orgnlGrpInfAndStsField;
        
        private OriginalPaymentInformationSEPA[] orgnlPmtInfAndStsField;
        
        /// <remarks/>
        public GroupHeaderSEPA GrpHdr {
            get {
                return this.grpHdrField;
            }
            set {
                this.grpHdrField = value;
            }
        }
        
        /// <remarks/>
        public OriginalGroupInformationSEPA OrgnlGrpInfAndSts {
            get {
                return this.orgnlGrpInfAndStsField;
            }
            set {
                this.orgnlGrpInfAndStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgnlPmtInfAndSts")]
        public OriginalPaymentInformationSEPA[] OrgnlPmtInfAndSts {
            get {
                return this.orgnlPmtInfAndStsField;
            }
            set {
                this.orgnlPmtInfAndStsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class GroupHeaderSEPA {
        
        private string msgIdField;
        
        private System.DateTime creDtTmField;
        
        private BranchAndFinancialInstitutionIdentificationSEPA1 itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDtTm {
            get {
                return this.creDtTmField;
            }
            set {
                this.creDtTmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CdtrAgt", typeof(BranchAndFinancialInstitutionIdentificationSEPA1))]
        [System.Xml.Serialization.XmlElementAttribute("DbtrAgt", typeof(BranchAndFinancialInstitutionIdentificationSEPA1))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public BranchAndFinancialInstitutionIdentificationSEPA1 Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class BranchAndFinancialInstitutionIdentificationSEPA1 {
        
        private FinancialInstitutionIdentificationSEPA1 finInstnIdField;
        
        /// <remarks/>
        public FinancialInstitutionIdentificationSEPA1 FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class FinancialInstitutionIdentificationSEPA1 {
        
        private string bICField;
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class OthrIdentification {
        
        private OthrIdentificationCode idField;
        
        /// <remarks/>
        public OthrIdentificationCode Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public enum OthrIdentificationCode {
        
        /// <remarks/>
        NOTPROVIDED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class FinancialInstitutionIdentificationSEPA3 {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(OthrIdentification))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class BranchAndFinancialInstitutionIdentificationSEPA3 {
        
        private FinancialInstitutionIdentificationSEPA3 finInstnIdField;
        
        /// <remarks/>
        public FinancialInstitutionIdentificationSEPA3 FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class CashAccountSEPA1 {
        
        private AccountIdentificationSEPA idField;
        
        private string ccyField;
        
        /// <remarks/>
        public AccountIdentificationSEPA Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class AccountIdentificationSEPA {
        
        private string iBANField;
        
        /// <remarks/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PostalAddressSEPA {
        
        private string ctryField;
        
        private string[] adrLineField;
        
        /// <remarks/>
        public string Ctry {
            get {
                return this.ctryField;
            }
            set {
                this.ctryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
        public string[] AdrLine {
            get {
                return this.adrLineField;
            }
            set {
                this.adrLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PartyIdentificationSEPA2 {
        
        private string nmField;
        
        private PostalAddressSEPA pstlAdrField;
        
        private PartySEPAChoice idField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddressSEPA PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public PartySEPAChoice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PartySEPAChoice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgId", typeof(OrganisationIdentificationSEPAChoice))]
        [System.Xml.Serialization.XmlElementAttribute("PrvtId", typeof(PersonIdentificationSEPA1Choice))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class OrganisationIdentificationSEPAChoice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BICOrBEI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericOrganisationIdentification1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class GenericOrganisationIdentification1 {
        
        private string idField;
        
        private OrganisationIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public OrganisationIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class OrganisationIdentificationSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PersonIdentificationSEPA1Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DtAndPlcOfBirth", typeof(DateAndPlaceOfBirth))]
        [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericPersonIdentification1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class DateAndPlaceOfBirth {
        
        private System.DateTime birthDtField;
        
        private string prvcOfBirthField;
        
        private string cityOfBirthField;
        
        private string ctryOfBirthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BirthDt {
            get {
                return this.birthDtField;
            }
            set {
                this.birthDtField = value;
            }
        }
        
        /// <remarks/>
        public string PrvcOfBirth {
            get {
                return this.prvcOfBirthField;
            }
            set {
                this.prvcOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CityOfBirth {
            get {
                return this.cityOfBirthField;
            }
            set {
                this.cityOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfBirth {
            get {
                return this.ctryOfBirthField;
            }
            set {
                this.ctryOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class GenericPersonIdentification1 {
        
        private string idField;
        
        private PersonIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public PersonIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PersonIdentificationSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType3 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType3 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03", IncludeInSchema=false)]
    public enum ItemChoiceType3 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PartyIdentificationSEPA1 {
        
        private string nmField;
        
        private PartySEPAChoice idField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PartySEPAChoice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class CreditorReferenceTypeCodeSEPA {
        
        private DocumentType3CodeSEPA cdField;
        
        /// <remarks/>
        public DocumentType3CodeSEPA Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public enum DocumentType3CodeSEPA {
        
        /// <remarks/>
        SCOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class CreditorReferenceTypeSEPA {
        
        private CreditorReferenceTypeCodeSEPA cdOrPrtryField;
        
        private string issrField;
        
        /// <remarks/>
        public CreditorReferenceTypeCodeSEPA CdOrPrtry {
            get {
                return this.cdOrPrtryField;
            }
            set {
                this.cdOrPrtryField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class CreditorReferenceInformationSEPA {
        
        private CreditorReferenceTypeSEPA tpField;
        
        private string refField;
        
        /// <remarks/>
        public CreditorReferenceTypeSEPA Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class StructuredRemittanceInformationSEPA2 {
        
        private CreditorReferenceInformationSEPA cdtrRefInfField;
        
        /// <remarks/>
        public CreditorReferenceInformationSEPA CdtrRefInf {
            get {
                return this.cdtrRefInfField;
            }
            set {
                this.cdtrRefInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class RemittanceInformationSEPA2Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Strd", typeof(StructuredRemittanceInformationSEPA2))]
        [System.Xml.Serialization.XmlElementAttribute("Ustrd", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class RestrictedFinancialIdentificationSEPA {
        
        private RestrictedSMNDACode idField;
        
        /// <remarks/>
        public RestrictedSMNDACode Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public enum RestrictedSMNDACode {
        
        /// <remarks/>
        SMNDA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class FinancialInstitutionIdentificationSEPA2 {
        
        private RestrictedFinancialIdentificationSEPA othrField;
        
        /// <remarks/>
        public RestrictedFinancialIdentificationSEPA Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class BranchAndFinancialInstitutionIdentificationSEPA2 {
        
        private FinancialInstitutionIdentificationSEPA2 finInstnIdField;
        
        /// <remarks/>
        public FinancialInstitutionIdentificationSEPA2 FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class CashAccountSEPA2 {
        
        private AccountIdentificationSEPA idField;
        
        /// <remarks/>
        public AccountIdentificationSEPA Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PartyIdentificationSEPA4 {
        
        private string nmField;
        
        private PartySEPA2 idField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PartySEPA2 Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PartySEPA2 {
        
        private PersonIdentificationSEPA2 prvtIdField;
        
        /// <remarks/>
        public PersonIdentificationSEPA2 PrvtId {
            get {
                return this.prvtIdField;
            }
            set {
                this.prvtIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PersonIdentificationSEPA2 {
        
        private RestrictedPersonIdentificationSEPA othrField;
        
        /// <remarks/>
        public RestrictedPersonIdentificationSEPA Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class RestrictedPersonIdentificationSEPA {
        
        private string idField;
        
        private RestrictedPersonIdentificationSchemeNameSEPA schmeNmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public RestrictedPersonIdentificationSchemeNameSEPA SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class RestrictedPersonIdentificationSchemeNameSEPA {
        
        private IdentificationSchemeNameSEPA prtryField;
        
        /// <remarks/>
        public IdentificationSchemeNameSEPA Prtry {
            get {
                return this.prtryField;
            }
            set {
                this.prtryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public enum IdentificationSchemeNameSEPA {
        
        /// <remarks/>
        SEPA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class AmendmentInformationDetailsSEPA {
        
        private string orgnlMndtIdField;
        
        private PartyIdentificationSEPA4 orgnlCdtrSchmeIdField;
        
        private CashAccountSEPA2 orgnlDbtrAcctField;
        
        private BranchAndFinancialInstitutionIdentificationSEPA2 orgnlDbtrAgtField;
        
        /// <remarks/>
        public string OrgnlMndtId {
            get {
                return this.orgnlMndtIdField;
            }
            set {
                this.orgnlMndtIdField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationSEPA4 OrgnlCdtrSchmeId {
            get {
                return this.orgnlCdtrSchmeIdField;
            }
            set {
                this.orgnlCdtrSchmeIdField = value;
            }
        }
        
        /// <remarks/>
        public CashAccountSEPA2 OrgnlDbtrAcct {
            get {
                return this.orgnlDbtrAcctField;
            }
            set {
                this.orgnlDbtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentificationSEPA2 OrgnlDbtrAgt {
            get {
                return this.orgnlDbtrAgtField;
            }
            set {
                this.orgnlDbtrAgtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class MandateRelatedInformationSEPA {
        
        private string mndtIdField;
        
        private System.DateTime dtOfSgntrField;
        
        private bool dtOfSgntrFieldSpecified;
        
        private bool amdmntIndField;
        
        private bool amdmntIndFieldSpecified;
        
        private AmendmentInformationDetailsSEPA amdmntInfDtlsField;
        
        private string elctrncSgntrField;
        
        /// <remarks/>
        public string MndtId {
            get {
                return this.mndtIdField;
            }
            set {
                this.mndtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DtOfSgntr {
            get {
                return this.dtOfSgntrField;
            }
            set {
                this.dtOfSgntrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DtOfSgntrSpecified {
            get {
                return this.dtOfSgntrFieldSpecified;
            }
            set {
                this.dtOfSgntrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AmdmntInd {
            get {
                return this.amdmntIndField;
            }
            set {
                this.amdmntIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmdmntIndSpecified {
            get {
                return this.amdmntIndFieldSpecified;
            }
            set {
                this.amdmntIndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public AmendmentInformationDetailsSEPA AmdmntInfDtls {
            get {
                return this.amdmntInfDtlsField;
            }
            set {
                this.amdmntInfDtlsField = value;
            }
        }
        
        /// <remarks/>
        public string ElctrncSgntr {
            get {
                return this.elctrncSgntrField;
            }
            set {
                this.elctrncSgntrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class CategoryPurposeSEPA {
        
        private string cdField;
        
        /// <remarks/>
        public string Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class LocalInstrumentSEPA {
        
        private string cdField;
        
        /// <remarks/>
        public string Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class ServiceLevelSEPA {
        
        private string cdField;
        
        /// <remarks/>
        public string Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PaymentTypeInformationSEPA {
        
        private Priority2Code instrPrtyField;
        
        private bool instrPrtyFieldSpecified;
        
        private ServiceLevelSEPA svcLvlField;
        
        private LocalInstrumentSEPA lclInstrmField;
        
        private SequenceType1Code seqTpField;
        
        private bool seqTpFieldSpecified;
        
        private CategoryPurposeSEPA ctgyPurpField;
        
        /// <remarks/>
        public Priority2Code InstrPrty {
            get {
                return this.instrPrtyField;
            }
            set {
                this.instrPrtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstrPrtySpecified {
            get {
                return this.instrPrtyFieldSpecified;
            }
            set {
                this.instrPrtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ServiceLevelSEPA SvcLvl {
            get {
                return this.svcLvlField;
            }
            set {
                this.svcLvlField = value;
            }
        }
        
        /// <remarks/>
        public LocalInstrumentSEPA LclInstrm {
            get {
                return this.lclInstrmField;
            }
            set {
                this.lclInstrmField = value;
            }
        }
        
        /// <remarks/>
        public SequenceType1Code SeqTp {
            get {
                return this.seqTpField;
            }
            set {
                this.seqTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeqTpSpecified {
            get {
                return this.seqTpFieldSpecified;
            }
            set {
                this.seqTpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CategoryPurposeSEPA CtgyPurp {
            get {
                return this.ctgyPurpField;
            }
            set {
                this.ctgyPurpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public enum Priority2Code {
        
        /// <remarks/>
        HIGH,
        
        /// <remarks/>
        NORM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public enum SequenceType1Code {
        
        /// <remarks/>
        FRST,
        
        /// <remarks/>
        RCUR,
        
        /// <remarks/>
        FNAL,
        
        /// <remarks/>
        OOFF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PartyIdentificationSEPA3 {
        
        private PartySEPA2 idField;
        
        /// <remarks/>
        public PartySEPA2 Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class ActiveOrHistoricCurrencyAndAmountSEPA {
        
        private ActiveOrHistoricCurrencyCodeEUR ccyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ActiveOrHistoricCurrencyCodeEUR Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public enum ActiveOrHistoricCurrencyCodeEUR {
        
        /// <remarks/>
        EUR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class AmountTypeSEPA {
        
        private ActiveOrHistoricCurrencyAndAmountSEPA instdAmtField;
        
        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmountSEPA InstdAmt {
            get {
                return this.instdAmtField;
            }
            set {
                this.instdAmtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class OriginalTransactionReferenceSEPA {
        
        private AmountTypeSEPA amtField;
        
        private System.DateTime itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private PartyIdentificationSEPA3 cdtrSchmeIdField;
        
        private PaymentTypeInformationSEPA pmtTpInfField;
        
        private PaymentMethodSEPACode pmtMtdField;
        
        private bool pmtMtdFieldSpecified;
        
        private MandateRelatedInformationSEPA mndtRltdInfField;
        
        private RemittanceInformationSEPA2Choice rmtInfField;
        
        private PartyIdentificationSEPA1 ultmtDbtrField;
        
        private PartyIdentificationSEPA2 dbtrField;
        
        private CashAccountSEPA1 dbtrAcctField;
        
        private BranchAndFinancialInstitutionIdentificationSEPA3 dbtrAgtField;
        
        private BranchAndFinancialInstitutionIdentificationSEPA3 cdtrAgtField;
        
        private PartyIdentificationSEPA2 cdtrField;
        
        private CashAccountSEPA1 cdtrAcctField;
        
        private PartyIdentificationSEPA1 ultmtCdtrField;
        
        /// <remarks/>
        public AmountTypeSEPA Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReqdColltnDt", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlElementAttribute("ReqdExctnDt", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public System.DateTime Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationSEPA3 CdtrSchmeId {
            get {
                return this.cdtrSchmeIdField;
            }
            set {
                this.cdtrSchmeIdField = value;
            }
        }
        
        /// <remarks/>
        public PaymentTypeInformationSEPA PmtTpInf {
            get {
                return this.pmtTpInfField;
            }
            set {
                this.pmtTpInfField = value;
            }
        }
        
        /// <remarks/>
        public PaymentMethodSEPACode PmtMtd {
            get {
                return this.pmtMtdField;
            }
            set {
                this.pmtMtdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PmtMtdSpecified {
            get {
                return this.pmtMtdFieldSpecified;
            }
            set {
                this.pmtMtdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public MandateRelatedInformationSEPA MndtRltdInf {
            get {
                return this.mndtRltdInfField;
            }
            set {
                this.mndtRltdInfField = value;
            }
        }
        
        /// <remarks/>
        public RemittanceInformationSEPA2Choice RmtInf {
            get {
                return this.rmtInfField;
            }
            set {
                this.rmtInfField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationSEPA1 UltmtDbtr {
            get {
                return this.ultmtDbtrField;
            }
            set {
                this.ultmtDbtrField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationSEPA2 Dbtr {
            get {
                return this.dbtrField;
            }
            set {
                this.dbtrField = value;
            }
        }
        
        /// <remarks/>
        public CashAccountSEPA1 DbtrAcct {
            get {
                return this.dbtrAcctField;
            }
            set {
                this.dbtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentificationSEPA3 DbtrAgt {
            get {
                return this.dbtrAgtField;
            }
            set {
                this.dbtrAgtField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentificationSEPA3 CdtrAgt {
            get {
                return this.cdtrAgtField;
            }
            set {
                this.cdtrAgtField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationSEPA2 Cdtr {
            get {
                return this.cdtrField;
            }
            set {
                this.cdtrField = value;
            }
        }
        
        /// <remarks/>
        public CashAccountSEPA1 CdtrAcct {
            get {
                return this.cdtrAcctField;
            }
            set {
                this.cdtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationSEPA1 UltmtCdtr {
            get {
                return this.ultmtCdtrField;
            }
            set {
                this.ultmtCdtrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        ReqdColltnDt,
        
        /// <remarks/>
        ReqdExctnDt,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public enum PaymentMethodSEPACode {
        
        /// <remarks/>
        TRF,
        
        /// <remarks/>
        DD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PaymentTransactionInformationSEPA {
        
        private string stsIdField;
        
        private string orgnlInstrIdField;
        
        private string orgnlEndToEndIdField;
        
        private TransactionIndividualStatusCodeSEPA txStsField;
        
        private bool txStsFieldSpecified;
        
        private StatusReasonInformationSEPA[] stsRsnInfField;
        
        private OriginalTransactionReferenceSEPA orgnlTxRefField;
        
        /// <remarks/>
        public string StsId {
            get {
                return this.stsIdField;
            }
            set {
                this.stsIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrgnlInstrId {
            get {
                return this.orgnlInstrIdField;
            }
            set {
                this.orgnlInstrIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrgnlEndToEndId {
            get {
                return this.orgnlEndToEndIdField;
            }
            set {
                this.orgnlEndToEndIdField = value;
            }
        }
        
        /// <remarks/>
        public TransactionIndividualStatusCodeSEPA TxSts {
            get {
                return this.txStsField;
            }
            set {
                this.txStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TxStsSpecified {
            get {
                return this.txStsFieldSpecified;
            }
            set {
                this.txStsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StsRsnInf")]
        public StatusReasonInformationSEPA[] StsRsnInf {
            get {
                return this.stsRsnInfField;
            }
            set {
                this.stsRsnInfField = value;
            }
        }
        
        /// <remarks/>
        public OriginalTransactionReferenceSEPA OrgnlTxRef {
            get {
                return this.orgnlTxRefField;
            }
            set {
                this.orgnlTxRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public enum TransactionIndividualStatusCodeSEPA {
        
        /// <remarks/>
        RJCT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class StatusReasonInformationSEPA {
        
        private PartyIdentificationSEPA6Choice orgtrField;
        
        private StatusReasonSEPA rsnField;
        
        /// <remarks/>
        public PartyIdentificationSEPA6Choice Orgtr {
            get {
                return this.orgtrField;
            }
            set {
                this.orgtrField = value;
            }
        }
        
        /// <remarks/>
        public StatusReasonSEPA Rsn {
            get {
                return this.rsnField;
            }
            set {
                this.rsnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PartyIdentificationSEPA6Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Id", typeof(PartySEPA1))]
        [System.Xml.Serialization.XmlElementAttribute("Nm", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class PartySEPA1 {
        
        private OrganisationIdentificationSEPA orgIdField;
        
        /// <remarks/>
        public OrganisationIdentificationSEPA OrgId {
            get {
                return this.orgIdField;
            }
            set {
                this.orgIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class OrganisationIdentificationSEPA {
        
        private string bICOrBEIField;
        
        /// <remarks/>
        public string BICOrBEI {
            get {
                return this.bICOrBEIField;
            }
            set {
                this.bICOrBEIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class StatusReasonSEPA {
        
        private string cdField;
        
        /// <remarks/>
        public string Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class OriginalPaymentInformationSEPA {
        
        private string orgnlPmtInfIdField;
        
        private string orgnlNbOfTxsField;
        
        private decimal orgnlCtrlSumField;
        
        private bool orgnlCtrlSumFieldSpecified;
        
        private TransactionGroupStatusCodeSEPA pmtInfStsField;
        
        private bool pmtInfStsFieldSpecified;
        
        private StatusReasonInformationSEPA[] stsRsnInfField;
        
        private PaymentTransactionInformationSEPA[] txInfAndStsField;
        
        /// <remarks/>
        public string OrgnlPmtInfId {
            get {
                return this.orgnlPmtInfIdField;
            }
            set {
                this.orgnlPmtInfIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrgnlNbOfTxs {
            get {
                return this.orgnlNbOfTxsField;
            }
            set {
                this.orgnlNbOfTxsField = value;
            }
        }
        
        /// <remarks/>
        public decimal OrgnlCtrlSum {
            get {
                return this.orgnlCtrlSumField;
            }
            set {
                this.orgnlCtrlSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrgnlCtrlSumSpecified {
            get {
                return this.orgnlCtrlSumFieldSpecified;
            }
            set {
                this.orgnlCtrlSumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TransactionGroupStatusCodeSEPA PmtInfSts {
            get {
                return this.pmtInfStsField;
            }
            set {
                this.pmtInfStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PmtInfStsSpecified {
            get {
                return this.pmtInfStsFieldSpecified;
            }
            set {
                this.pmtInfStsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StsRsnInf")]
        public StatusReasonInformationSEPA[] StsRsnInf {
            get {
                return this.stsRsnInfField;
            }
            set {
                this.stsRsnInfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TxInfAndSts")]
        public PaymentTransactionInformationSEPA[] TxInfAndSts {
            get {
                return this.txInfAndStsField;
            }
            set {
                this.txInfAndStsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public enum TransactionGroupStatusCodeSEPA {
        
        /// <remarks/>
        RJCT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03")]
    public partial class OriginalGroupInformationSEPA {
        
        private string orgnlMsgIdField;
        
        private string orgnlMsgNmIdField;
        
        private string orgnlNbOfTxsField;
        
        private decimal orgnlCtrlSumField;
        
        private bool orgnlCtrlSumFieldSpecified;
        
        private TransactionGroupStatusCodeSEPA grpStsField;
        
        private bool grpStsFieldSpecified;
        
        private StatusReasonInformationSEPA[] stsRsnInfField;
        
        /// <remarks/>
        public string OrgnlMsgId {
            get {
                return this.orgnlMsgIdField;
            }
            set {
                this.orgnlMsgIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrgnlMsgNmId {
            get {
                return this.orgnlMsgNmIdField;
            }
            set {
                this.orgnlMsgNmIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrgnlNbOfTxs {
            get {
                return this.orgnlNbOfTxsField;
            }
            set {
                this.orgnlNbOfTxsField = value;
            }
        }
        
        /// <remarks/>
        public decimal OrgnlCtrlSum {
            get {
                return this.orgnlCtrlSumField;
            }
            set {
                this.orgnlCtrlSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrgnlCtrlSumSpecified {
            get {
                return this.orgnlCtrlSumFieldSpecified;
            }
            set {
                this.orgnlCtrlSumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TransactionGroupStatusCodeSEPA GrpSts {
            get {
                return this.grpStsField;
            }
            set {
                this.grpStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GrpStsSpecified {
            get {
                return this.grpStsFieldSpecified;
            }
            set {
                this.grpStsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StsRsnInf")]
        public StatusReasonInformationSEPA[] StsRsnInf {
            get {
                return this.stsRsnInfField;
            }
            set {
                this.stsRsnInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.002.003.03", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        CdtrAgt,
        
        /// <remarks/>
        DbtrAgt,
    }
}
